<a href="https://colab.research.google.com/github/Leonela180/Practica_calificada/blob/main/Practica_Calificada1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PRACTICA CALIFICADA

## EJERCICIO 1

In [ ]:
import numpy as np

In [ ]:
#crear un vector de numeros enteros del 1 al 20
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
#crear una matriz de 3x3 con valores aleatorios entre 0 y 1
np.random.random((3,3))


array([[0.12904595, 0.72806884, 0.10063054],
       [0.53545464, 0.74982772, 0.89299621],
       [0.76633774, 0.88734488, 0.70883811]])

In [ ]:
#Redimenciona una matriz de 4x4 a una matriz de 2x8
matriz1 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12],[13, 14, 15, 16]])
# Redimensionar a 2x8
matriz2 = matriz1.reshape((2, 8))

print("Matriz original (4x4):\n", matriz1)
print("\nMatriz redimensionada (2x8):\n", matriz2)

Matriz original (4x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Matriz redimensionada (2x8):
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [ ]:
#crea un array de 10 numeros equidistantes entre 0 y 1
np.linspace(0,1,10)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
#concatena dos vectores vertical y hirizontalmente
vector1 = np.random.randint(1,10,6)
vector2 = vector1.reshape(3,2)
print("Concatenacion Horizontal\n", vector1)
print("\nConcatenacion Vertical\n", vector2)

Concatenacion Horizontal
 [3 2 9 4 6 1]

Concatenacion Vertical
 [[3 2]
 [9 4]
 [6 1]]


## EJERCICIO 2

In [ ]:
#Calcular la suma, resta, multiplicacion y division de dos vectores
vector1 = np.array([6, 5, 4, 2, 7])
vector2 = np.array([1, 3, 8, 9, 4])

suma = np.add(vector1,vector2)
resta = np.subtract(vector1,vector2)
multi = np.multiply(vector1,vector2)
div = np.divide(vector1,vector2)

print("Suma\n",suma)
print("Resta\n",resta)
print("Multiplicacion\n",multi)
print("Division\n",div)

Suma
 [ 7  8 12 11 11]
Resta
 [ 5  2 -4 -7  3]
Multiplicacion
 [ 6 15 32 18 28]
Division
 [6.         1.66666667 0.5        0.22222222 1.75      ]


In [ ]:
#Calcula la media, mediana y desviacion estandar de un vector
vector1 = np.random.randint(1,10,6)
print("Vector\n",vector1)
print("------------------")
media = np.mean(vector1)
mediana = np.median(vector1)
desviacion = np.std(vector1)

print("Media\n",media)
print("Mediana\n",mediana)
print("Desviacion Estandar\n",desviacion)

Vector
 [8 7 8 2 6 8]
------------------
Media
 6.5
Mediana
 7.5
Desviacion Estandar
 2.140872096444188


In [ ]:
#Normaliza un vector dividiendo cada elemento por el valor maximo
vector1 = np.random.randint(1,10,6)
print("Vector\n",vector1)
print("------------------")
maximo = np.max(vector1)
div= vector1/maximo
print("Vector Normalizado\n",div)

Vector
 [2 4 6 1 9 2]
------------------
Vector Normalizado
 [0.22222222 0.44444444 0.66666667 0.11111111 1.         0.22222222]


In [ ]:
#Encuentre el indice del valor maximo y min de un vector
vector1 = np.random.randint(1,10,6)
print("Vector\n",vector1)
print("------------------")
maximo = np.max(vector1)
in_max = np.argmax(vector1)
minimo = np.min(vector1)
in_min = np.argmin(vector1)

print("Valor maximo\n",maximo)
print("Valor minimo\n",minimo)
print("Indice del valor maximo\n",in_max)
print("Indice del valor minimo\n",in_min)

Vector
 [4 4 4 9 7 8]
------------------
Valor maximo
 9
Valor minimo
 4
Indice del valor maximo
 3
Indice del valor minimo
 0


In [ ]:
#Realiza una multiplicacion matricial entre dos matrices 3x3
matriz1 = np.random.randint(1,10,9).reshape(3,3)
matriz2 = np.random.randint(1,10,9).reshape(3,3)
print("Primera matriz\n",matriz1)
print("Segunda matriz\n",matriz2)
print("------------------")
multi = np.dot(matriz1,matriz2)
print("Multiplicacion\n",multi)


Primera matriz
 [[8 6 4]
 [1 5 9]
 [5 4 6]]
Segunda matriz
 [[2 9 1]
 [2 6 9]
 [9 5 7]]
------------------
Multiplicacion
 [[ 64 128  90]
 [ 93  84 109]
 [ 72  99  83]]


## EJERCICIO 3

In [ ]:
#selecione los elementos pares de un vector de numeros enteros
vector = np.random.randint(1,10,6)
print("Vector\n",vector1)
print("------------------")
pares = vector1[vector%2==0]
print("Pares\n",pares)


Vector
 [4 6 6 3 3 8]
------------------
Pares
 [4 6 6 3]


In [ ]:
#Filtra los valores mayores que 5 en un vector
vector = np.random.randint(1,10,6)
print("Vector\n",vector)
print("------------------")
mayores = vector[vector>5]
mayor = vector>5
print("Mayores a 5\n",mayores)
print("Mayores a 5\n",mayor)

Vector
 [1 6 4 3 5 4]
------------------
Mayores a 5
 [6]
Mayores a 5
 [False  True False False False False]


In [ ]:
#Filtrar los valores iguales a 0
vector = np.random.randint(1,10,6)
print("Vector\n",vector)
print("------------------")
ceros = vector[vector==0]
cero = vector==0
print("Ceros\n",ceros)
print("Ceros\n",cero)

Vector
 [5 7 5 6 4 5]
------------------
Ceros
 []
Ceros
 [False False False False False False]


In [ ]:
#Filtrar los valores negativos
vector = np.random.randint(1,10,6)
print("Vector\n",vector)
print("------------------")
nega = vector[vector<0]
negativo = vector<0
print("Negativo \n",nega)
print("Negativo \n",negativo)

Vector
 [9 6 7 6 7 1]
------------------
Negativo 
 []
Negativo 
 [False False False False False False]


In [ ]:
#Aplicar la media a los valores mayores de 50
vector = np.array([1,80,90,40,5,60,70])
print("Vector\n",vector)
print("------------------")
media = np.mean(vector[vector>50])
print("Media\n",media)

Vector
 [ 1 80 90 40  5 60 70]
------------------
Media
 75.0


## EJERCICIO 4

In [ ]:
#Crea un vector de 10 elementos y remplaza todos los valores mayores a 5 con 0
vector = np.random.randint(1,10,10)
print("Vector\n",vector)
print("------------------")
vector[vector>5]=0
print("Vector\n",vector)


Vector
 [7 9 9 5 5 1 2 1 8 6]
------------------
Vector
 [0 0 0 5 5 1 2 1 0 0]


In [ ]:
#Combina dos vectores booleanos utilizando las operaciones & y or
vector1 = np.array([True, False, True, False])
vector2 = np.array([False, True, False, True])
print("Vector 1\n",vector1)
print("Vector 2\n",vector2)
print("------------------")
and_ = np.logical_and(vector1,vector2)
or_ = np.logical_or(vector1,vector2)
print("And\n",and_)
print("Or\n",or_)

Vector 1
 [ True False  True False]
Vector 2
 [False  True False  True]
------------------
And
 [False False False False]
Or
 [ True  True  True  True]


In [3]:
#cuenta la cantidad de valores en un vector que son multiplos de 3
import numpy as np
vector = np.random.randint(1,10,10)
print("Vector\n",vector)
print("------------------")
multi = vector[vector%3==0]
print("Multiplos de 3\n",multi)
print("Cantidad de multiplos de 3\n",len(multi))

Vector
 [3 4 9 4 4 9 2 8 2 5]
------------------
Multiplos de 3
 [3 9 9]
Cantidad de multiplos de 3
 3


In [4]:
#Enuentra los indices de los elementos no nulos en un vector (npnonzro)
vector = np.array([1, 0, 2, 0, 3, 0, 4, 0])
print("Vector\n",vector)
print("------------------")
indices = np.nonzero(vector)
print("Indices\n",indices)

Vector
 [1 0 2 0 3 0 4 0]
------------------
Indices
 (array([0, 2, 4, 6]),)


In [5]:
#Comprueba si todos los elementos en un array son mayores que un valor especifico digitado por el usuario
vector = np.random.randint(1,10,10)
print("Vector\n",vector)
print("------------------")
valor = int(input("Ingrese un valor: "))
mayor = np.all(vector>valor)
print

Vector
 [7 5 4 9 8 5 3 6 5 1]
------------------
Ingrese un valor: 4


<function print(*args, sep=' ', end='\n', file=None, flush=False)>

## EJERCICIO 5

In [6]:
#Calcula el cuadro de cada elemento de un vector
vector = np.random.randint(1,10,10)
print("Vector\n",vector)
print("------------------")
cuadrado = np.square(vector)
print("Cuadrado\n",cuadrado)

Vector
 [5 7 4 3 2 6 3 3 4 7]
------------------
Cuadrado
 [25 49 16  9  4 36  9  9 16 49]


In [7]:
#Utiliza la funion exponenial para elvar todo los elementos de un vector a la misma potencia
vector = np.random.randint(1,10,10)
print("Vector\n",vector)
print("------------------")
potencia = np.exp(vector)
print("Potencia\n",potencia)

Vector
 [4 3 7 5 3 5 5 2 2 2]
------------------
Potencia
 [  54.59815003   20.08553692 1096.63315843  148.4131591    20.08553692
  148.4131591   148.4131591     7.3890561     7.3890561     7.3890561 ]


In [8]:
#Encuentra los valores maximos y minimos en cada fila de una matriz
matriz = np.random.randint(1,10,9).reshape(3,3)
print("Matriz\n",matriz)
print("------------------")
maximo = np.max(matriz,axis=1)
minimo = np.min(matriz,axis=1)
print("Maximo\n",maximo)
print("Minimo\n",minimo)

Matriz
 [[7 8 1]
 [2 9 3]
 [7 1 5]]
------------------
Maximo
 [8 9 7]
Minimo
 [1 2 1]


In [9]:
#Aplica la funion sin a todos los elementos de un vector y almacena los resultado en otro vector
vector = np.random.randint(1,10,10)
print("Vector\n",vector)
print("------------------")
sin = np.sin(vector)
print("Sin\n",sin)


Vector
 [8 3 9 7 8 7 7 2 1 8]
------------------
Sin
 [0.98935825 0.14112001 0.41211849 0.6569866  0.98935825 0.6569866
 0.6569866  0.90929743 0.84147098 0.98935825]


In [10]:
#realiza la transpuesta de una matriz 3x4
matriz = np.random.randint(1,10,12).reshape(3,4)
print("Matriz\n",matriz)
print("------------------")
transpuesta = np.transpose(matriz)
print("Transpuesta\n",transpuesta)

Matriz
 [[9 1 3 8]
 [3 4 2 8]
 [3 2 5 3]]
------------------
Transpuesta
 [[9 3 3]
 [1 4 2]
 [3 2 5]
 [8 8 3]]


## EJERCICIO 6

In [11]:
import pandas as pd

In [12]:
data = {
    'Nombre': ['Ana', 'Luis', 'Carlos', 'María', 'Jorge', 'Lucía', 'Pedro', 'Sofía', 'Raúl', 'Elena'],
    'Edad': [24, 30, 22, 28, 35, 26, 20, 40, 32, 27],
    'Ciudad': ['Madrid', 'Barcelona', 'Madrid', 'Sevilla', 'Madrid', 'Barcelona', 'Valencia', 'Sevilla', 'Madrid', 'Valencia']
}

df = pd.DataFrame(data)
print("DataFrame original:")
print(df)

# 2. Filtrar a las personas con más de 25 años
filtro_mayores_25 = df[df['Edad'] > 25]
print("\nPersonas con más de 25 años:")
print(filtro_mayores_25)

# 3. Añadir nueva columna 'Ingresos'
df['Ingresos'] = [25000, 32000, 21000, 28000, 34000, 30000, 19000, 40000, 33000, 31000]
print("\nDataFrame con columna 'Ingresos':")
print(df)

# 4. Promedio de la edad
promedio_edad = df['Edad'].mean()
print("\nPromedio de edad:", promedio_edad)

# 5. Contar cuántas veces aparece cada ciudad
conteo_ciudades = df['Ciudad'].value_counts()
print("\nConteo de ciudades:")
print(conteo_ciudades)

# 6. Agrupar por ciudad y calcular promedio de edad
promedio_edad_por_ciudad = df.groupby('Ciudad')['Edad'].mean()
print("\nPromedio de edad por ciudad:")
print(promedio_edad_por_ciudad)

# 7. Ordenar por edad ascendente
df_ascendente = df.sort_values(by='Edad')
print("\nDataFrame ordenado por edad (ascendente):")
print(df_ascendente)

# 8. Ordenar por edad descendente
df_descendente = df.sort_values(by='Edad', ascending=False)
print("\nDataFrame ordenado por edad (descendente):")
print(df_descendente)

DataFrame original:
   Nombre  Edad     Ciudad
0     Ana    24     Madrid
1    Luis    30  Barcelona
2  Carlos    22     Madrid
3   María    28    Sevilla
4   Jorge    35     Madrid
5   Lucía    26  Barcelona
6   Pedro    20   Valencia
7   Sofía    40    Sevilla
8    Raúl    32     Madrid
9   Elena    27   Valencia

Personas con más de 25 años:
  Nombre  Edad     Ciudad
1   Luis    30  Barcelona
3  María    28    Sevilla
4  Jorge    35     Madrid
5  Lucía    26  Barcelona
7  Sofía    40    Sevilla
8   Raúl    32     Madrid
9  Elena    27   Valencia

DataFrame con columna 'Ingresos':
   Nombre  Edad     Ciudad  Ingresos
0     Ana    24     Madrid     25000
1    Luis    30  Barcelona     32000
2  Carlos    22     Madrid     21000
3   María    28    Sevilla     28000
4   Jorge    35     Madrid     34000
5   Lucía    26  Barcelona     30000
6   Pedro    20   Valencia     19000
7   Sofía    40    Sevilla     40000
8    Raúl    32     Madrid     33000
9   Elena    27   Valencia     31000

Pr

## EJERCICIO 7

In [20]:
#indicar cuantos son de la carrera de ing.Sistemas
import pandas as pd

df = pd.read_excel(file_path)
sis = df[df["Carrera"] == "Ing. en sistemas"]
print(sis)

   Num Control           Carrera  Semestre Inscripción  Id Persona
3     WiVaLó04  Ing. en sistemas         2  2016-12-03           4
9     BePaNa10  Ing. en sistemas         9  2018-05-15          10
21    ArLaOc22  Ing. en sistemas         1  2015-12-17          22
24    JaSoAy25  Ing. en sistemas         2  2018-05-21          25
26    DoAlVi27  Ing. en sistemas         4  2016-05-16          27
31    JuNúHi32  Ing. en sistemas         4  2016-05-22          32
45    TeLaKa46  Ing. en sistemas         4  2017-12-20          46
55    ViSaDu56  Ing. en sistemas         1  2017-12-22          56
73    LiToVe74  Ing. en sistemas         8  2015-12-12          74
82    FrViVa83  Ing. en sistemas         4  2016-12-12          83
89    LuÁvAl90  Ing. en sistemas         6  2017-12-19          90
91    FéVaRo92  Ing. en sistemas         6  2018-05-02          92
93    ArMuNi94  Ing. en sistemas        10  2015-05-07          94


In [19]:
#Indicar cuantos son de la carrera de Ing. en derecho
df = pd.read_excel(file_path)
derecho = df[df["Carrera"] == "Lic. en derecho"]
print(derecho)

   Num Control          Carrera  Semestre Inscripción  Id Persona
2     MaFeNú03  Lic. en derecho         6  2015-05-09           3
7     JaAgEs08  Lic. en derecho         7  2018-12-12           8
12    RaBeBu13  Lic. en derecho        10  2017-05-21          13
14    DeRuTr15  Lic. en derecho         8  2017-12-25          15
17    MaGaBe18  Lic. en derecho         1  2018-12-02          18
25    AsPoLa26  Lic. en derecho         6  2016-05-15          26
32    LiMáSa33  Lic. en derecho         5  2018-12-01          33
33    ÁlPrLi34  Lic. en derecho         2  2017-05-02          34
47    SeVaSa48  Lic. en derecho         6  2016-05-09          48
49    MoVaGa50  Lic. en derecho         7  2018-12-17          50
50    AdSaCa51  Lic. en derecho         3  2015-12-07          51
56    LaFeVe57  Lic. en derecho         7  2018-05-16          57
60    DiQuPa61  Lic. en derecho         9  2018-12-14          61
84    FéRiLa85  Lic. en derecho         4  2015-05-28          85
85    ClAr

In [22]:
#Indicar cuantos se inscribieron en el año 2015
df = pd.read_excel(file_path)
df['Año'] = df['Inscripción'].dt.year
año_2015 = df[df['Año'] == 2015]
print(año_2015)

   Num Control              Carrera  Semestre Inscripción  Id Persona   Año
0     SeNeTe01  Lic. en nutriología         7  2015-05-20           1  2015
1     JeViPi02         Ing. química         8  2015-05-02           2  2015
2     MaFeNú03      Lic. en derecho         6  2015-05-09           3  2015
5     AlAlEs06         Ing. química         9  2015-12-18           6  2015
8     ClHeAr09  Lic. en nutriología         4  2015-05-01           9  2015
21    ArLaOc22     Ing. en sistemas         1  2015-12-17          22  2015
27    AnLuLl28    Lic. en pedagogía         4  2015-12-13          28  2015
30    BrCuOc31    Lic. en pedagogía         1  2015-05-06          31  2015
37    KlFuVi38     Ing. mecatrónica         9  2015-05-06          38  2015
44    GoRuSa45         Ing. química         8  2015-12-06          45  2015
50    AdSaCa51      Lic. en derecho         3  2015-12-07          51  2015
59    LiMeAc60  Lic. en nutriología         3  2015-05-06          60  2015
65    PaViLa

In [28]:
#Indicar cuantos son del 1 y 2 semestre
df = pd.read_excel(file_path)
semestre_1 = df[df['Semestre'] == 1]
semestre_2 = df[df['Semestre'] == 2]
print(semestre_1)
print("----------------------------------------------------------------------")
print(semestre_2)

   Num Control              Carrera  Semestre Inscripción  Id Persona
6     SaMeSe07     Ing. mecatrónica         1  2018-12-02           7
17    MaGaBe18      Lic. en derecho         1  2018-12-02          18
21    ArLaOc22     Ing. en sistemas         1  2015-12-17          22
30    BrCuOc31    Lic. en pedagogía         1  2015-05-06          31
48    EuPrVi49         Ing. química         1  2016-05-13          49
55    ViSaDu56     Ing. en sistemas         1  2017-12-22          56
63    TeAlVa64     Ing. mecatrónica         1  2017-12-23          64
69    LuAgPa70         Ing. química         1  2016-12-07          70
75    IsRoVa76    Lic. en pedagogía         1  2018-05-27          76
77    ArMeLa78         Ing. química         1  2017-05-22          78
92    OrVeTr93  Lic. en nutriología         1  2015-05-03          93
----------------------------------------------------------------------
   Num Control              Carrera  Semestre Inscripción  Id Persona
3     WiVaLó04     