<a href="https://colab.research.google.com/github/Leonela180/Practica_calificada/blob/main/Practica_Calificada.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PRACTICA CALIFICADA

## EJERCICIO 1

In [5]:
import numpy as np

In [7]:
#crear un vector de numeros enteros del 1 al 20
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [19]:
#crear una matriz de 3x3 con valores aleatorios entre 0 y 1
np.random.random((3,3))


array([[0.12904595, 0.72806884, 0.10063054],
       [0.53545464, 0.74982772, 0.89299621],
       [0.76633774, 0.88734488, 0.70883811]])

In [31]:
#Redimenciona una matriz de 4x4 a una matriz de 2x8
matriz1 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12],[13, 14, 15, 16]])
# Redimensionar a 2x8
matriz2 = matriz1.reshape((2, 8))

print("Matriz original (4x4):\n", matriz1)
print("\nMatriz redimensionada (2x8):\n", matriz2)

Matriz original (4x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Matriz redimensionada (2x8):
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [21]:
#crea un array de 10 numeros equidistantes entre 0 y 1
np.linspace(0,1,10)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [30]:
#concatena dos vectores vertical y hirizontalmente
vector1 = np.random.randint(1,10,6)
vector2 = vector1.reshape(3,2)
print("Concatenacion Horizontal\n", vector1)
print("\nConcatenacion Vertical\n", vector2)

Concatenacion Horizontal
 [3 2 9 4 6 1]

Concatenacion Vertical
 [[3 2]
 [9 4]
 [6 1]]


## EJERCICIO 2

In [40]:
#Calcular la suma, resta, multiplicacion y division de dos vectores
vector1 = np.array([6, 5, 4, 2, 7])
vector2 = np.array([1, 3, 8, 9, 4])

suma = np.add(vector1,vector2)
resta = np.subtract(vector1,vector2)
multi = np.multiply(vector1,vector2)
div = np.divide(vector1,vector2)

print("Suma\n",suma)
print("Resta\n",resta)
print("Multiplicacion\n",multi)
print("Division\n",div)

Suma
 [ 7  8 12 11 11]
Resta
 [ 5  2 -4 -7  3]
Multiplicacion
 [ 6 15 32 18 28]
Division
 [6.         1.66666667 0.5        0.22222222 1.75      ]


In [46]:
#Calcula la media, mediana y desviacion estandar de un vector
vector1 = np.random.randint(1,10,6)
print("Vector\n",vector1)
print("------------------")
media = np.mean(vector1)
mediana = np.median(vector1)
desviacion = np.std(vector1)

print("Media\n",media)
print("Mediana\n",mediana)
print("Desviacion Estandar\n",desviacion)

Vector
 [8 7 8 2 6 8]
------------------
Media
 6.5
Mediana
 7.5
Desviacion Estandar
 2.140872096444188


In [48]:
#Normaliza un vector dividiendo cada elemento por el valor maximo
vector1 = np.random.randint(1,10,6)
print("Vector\n",vector1)
print("------------------")
maximo = np.max(vector1)
div= vector1/maximo
print("Vector Normalizado\n",div)

Vector
 [2 4 6 1 9 2]
------------------
Vector Normalizado
 [0.22222222 0.44444444 0.66666667 0.11111111 1.         0.22222222]


In [50]:
#Encuentre el indice del valor maximo y min de un vector
vector1 = np.random.randint(1,10,6)
print("Vector\n",vector1)
print("------------------")
maximo = np.max(vector1)
in_max = np.argmax(vector1)
minimo = np.min(vector1)
in_min = np.argmin(vector1)

print("Valor maximo\n",maximo)
print("Valor minimo\n",minimo)
print("Indice del valor maximo\n",in_max)
print("Indice del valor minimo\n",in_min)

Vector
 [4 4 4 9 7 8]
------------------
Valor maximo
 9
Valor minimo
 4
Indice del valor maximo
 3
Indice del valor minimo
 0


In [62]:
#Realiza una multiplicacion matricial entre dos matrices 3x3
matriz1 = np.random.randint(1,10,9).reshape(3,3)
matriz2 = np.random.randint(1,10,9).reshape(3,3)
print("Primera matriz\n",matriz1)
print("Segunda matriz\n",matriz2)
print("------------------")
multi = np.dot(matriz1,matriz2)
print("Multiplicacion\n",multi)


Primera matriz
 [[8 6 4]
 [1 5 9]
 [5 4 6]]
Segunda matriz
 [[2 9 1]
 [2 6 9]
 [9 5 7]]
------------------
Multiplicacion
 [[ 64 128  90]
 [ 93  84 109]
 [ 72  99  83]]


## EJERCICIO 3

In [65]:
#selecione los elementos pares de un vector de numeros enteros
vector = np.random.randint(1,10,6)
print("Vector\n",vector1)
print("------------------")
pares = vector1[vector%2==0]
print("Pares\n",pares)


Vector
 [4 6 6 3 3 8]
------------------
Pares
 [4 6 6 3]


In [72]:
#Filtra los valores mayores que 5 en un vector
vector = np.random.randint(1,10,6)
print("Vector\n",vector)
print("------------------")
mayores = vector[vector>5]
mayor = vector>5
print("Mayores a 5\n",mayores)
print("Mayores a 5\n",mayor)

Vector
 [1 6 4 3 5 4]
------------------
Mayores a 5
 [6]
Mayores a 5
 [False  True False False False False]


In [83]:
#Filtrar los valores iguales a 0
vector = np.random.randint(1,10,6)
print("Vector\n",vector)
print("------------------")
ceros = vector[vector==0]
cero = vector==0
print("Ceros\n",ceros)
print("Ceros\n",cero)

Vector
 [5 7 5 6 4 5]
------------------
Ceros
 []
Ceros
 [False False False False False False]


In [86]:
#Filtrar los valores negativos
vector = np.random.randint(1,10,6)
print("Vector\n",vector)
print("------------------")
nega = vector[vector<0]
negativo = vector<0
print("Negativo \n",nega)
print("Negativo \n",negativo)

Vector
 [9 6 7 6 7 1]
------------------
Negativo 
 []
Negativo 
 [False False False False False False]


In [88]:
#Aplicar la media a los valores mayores de 50
vector = np.array([1,80,90,40,5,60,70])
print("Vector\n",vector)
print("------------------")
media = np.mean(vector[vector>50])
print("Media\n",media)

Vector
 [ 1 80 90 40  5 60 70]
------------------
Media
 75.0


## EJERCICIO 4

In [89]:
#Crea un vector de 10 elementos y remplaza todos los valores mayores a 5 con 0
vector = np.random.randint(1,10,10)
print("Vector\n",vector)
print("------------------")
vector[vector>5]=0
print("Vector\n",vector)


Vector
 [7 9 9 5 5 1 2 1 8 6]
------------------
Vector
 [0 0 0 5 5 1 2 1 0 0]
